services:
  server:
    build:
      context: .
    volumes:
       - db_data_sqlite:/var/lib/kualat
       - custom:/kualat/custom
    environment:
      DB_FILENAME: "/var/lib/kualat/data.sqlite"
    ports:
      - 3000:3000
volumes:
  db_data_sqlite:
  custom: