name: docker-build-release

env:
   ghcr_repository: 'ghcr.io/dikaardnt/kualat'

on:
   release:
      types: [published]

jobs:
   ghcr-build-push:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
         - name: Checkout
           uses: actions/checkout@v4
         - name: Set up QEMU
           uses: docker/setup-qemu-action@v3
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3
         - name: Login to GHCR
           uses: docker/login-action@v3
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
         - name: Build and push
           uses: docker/build-push-action@v5
           with:
              platforms: linux/amd64,linux/arm64
              context: .
              push: true
              tags: |
                 ${{ env.ghcr_repository }}:${{ github.event.release.tag_name }}
                 ${{ env.ghcr_repository }}:latest
