name: docker-build-development

env:
   ghcr_repository: 'ghcr.io/dikaardnt/kualat'
   ghcr_tag: 'development'

on:
   push:
      branches:
         - develop

jobs:
   ghcr-build-push:
      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write
      steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Set up QEMU
           uses: docker/setup-qemu-action@v1
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v1
         - name: Login to GHCR
           uses: docker/login-action@v1
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
         - name: Build and push
           uses: docker/build-push-action@v2
           with:
              platforms: linux/amd64,linux/arm64
              context: .
              push: true
              tags: ${{ env.ghcr_repository }}:${{ env.ghcr_tag }}
